###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microsvc-test
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /microsvc-test
        backend:
          serviceName: microsvc-test
          servicePort: 8080
#      - path: /login
#        backend:
#          serviceName: microsvc-test
#          servicePort: 8080
